---
title: "UNFPA's Small Area Estimation Tools"
output: 
  html_document:
    toc: true
    toc_float: true
---

# Introduction

Small area estimation (SAE) is a set of statistical methods used to generate high-resolution spatial predictions from low-resolution data sources. In the context of human population characteristics, SAE methods often combine high-resolution census data with subject-specific but lower-resolution household surveys. 

This site provides an introduction the the UNFPA's small area estimation tools that have been developed to support estimation of SDG indicators from census and DHS data. At present, this includes a guide to conducting data harmonization between DHS survey and census data, and instructions for using the UNFPA's Small Area Estimation application. 

Future developments may include further tools for facilitating harmonization and indicator calculations, as well as an online version of the UNFPA's Small Area Estimation Guidance document that is the basis for the SAE tool and harmonization methods. 


# Software Requirements

Each of the tools presented here is built using the R programming environment. Code needed to run each tool  is hosted in the [UNFPA github site](https://github.com/unfpasae).  The tools  must be built on a user's laptop and requires prior installation of both [R](https://www.r-project.org/) and are best run in the [RStudio](https://posit.co/downloads/) integrated development environment. Finally, you will need to have [Git installed](https://github.com/git-guides/install-git). 

# Navigation

The topics mentioned above can be accessed using the tabs at the top of the page.  New topics will be added as they are developed.  Within each topic, chapters and subsections can be accessed in the sidebar. 


