
# Appendix: User-defined R functions

## compare_categories

```{r warning = FALSE, eval = FALSE}
compare_categories = function(ipums_data = NULL, ipums_var = NULL, ipums_weight = NULL,
                              dhs_data = NULL, dhs_var = NULL, dhs_weight = NULL) {
  # This function creates a weighted frequency table for a maximum of one IPUMS 
  # variable and one DHS variable. The purpose of this function is to easily compare
  # the categories and frequencies of potentially harmonizable IPUMS and DHS 
  # variables as a preliminary step in the harmonization process.
  #
  # Inputs:
  #   ipums_data = Name of the IPUMS data frame (e.g., "sl2015_ipums"). Must be 
  #                 entered as a string.
  #   ipums_var = Name of the variable in the IPUMS data frame for which the table
  #                 is to be constructed (e.g., "SL2015_MARST"). Must be entered
  #                 as a string.
  #   ipums_weight = Name of the variable in the IPUMS data frame corresponding to 
  #                   the weight variable (e.g., "PERWT"). Must be entered as a string.
  #   dhs_data = Name of the DHS data frame (e.g., "sl2019_dhs_ir"). Must be entered 
  #               as a string.
  #   dhs_var = Name of the variable in the DHS data frame for which the table is to 
  #               be constructed (e.g., "V501"). Must be entered as a string.
  #   dhs_weight = Name of the variable in the IPUMS data frame corresponding to the 
  #                 weight variable (e.g., "V005R"). Must be entered as a string.
  #
  # Prints:
  #   Two tables of weighted counts and percents: One for ipums_var, and one for dhs_var.
  #
  
  
  if(!any(is.null(ipums_data), is.null(ipums_var), is.null(ipums_weight))) {
    IPUMS = eval(parse(text = noquote(paste0(ipums_data, "$", ipums_var))))
    weight_ipums = eval(parse(text = noquote(paste0(ipums_data, "$", ipums_weight))))
    
    print(noquote(paste0("IPUMS weighted frequency table for ", ipums_var, ":")))
    print(fre(IPUMS, weight = weight_ipums)[, c(1:2, 4)])
    
    cat("\n\n\n")
  }
  
  if(!any(is.null(dhs_data), is.null(dhs_var), is.null(dhs_weight))) {
    DHS = eval(parse(text = noquote(paste0(dhs_data, "$", dhs_var))))
    weight_dhs = eval(parse(text = noquote(paste0(dhs_data, "$", dhs_weight))))
    
    print(noquote(paste0("DHS weighted frequency table for ", dhs_var, ":")))
    print(fre(DHS, weight = weight_dhs)[, c(1:2, 4)])
  }
}
```




## new_var_label

```{r warning = FALSE, eval = FALSE}
new_var_label = function(dataframe, label) {
  # This function appends a variable label to a data frame.
  #
  # Inputs:
  #   dataframe = The data frame to which the user would like to append a variable label.
  #   label = Variable label that the user would like to append to the data frame. Must be
  #           a string of characters; otherwise, the function will return an error message.
  #
  # Returns:
  #   An updated version of the dataframe that includes the new variable label.
  #
  
  attr(dataframe, "variable.labels") = c(attr(dataframe, "variable.labels"), label)
  
  return(dataframe)
}
```




## write_ipums_output

```{r warning = FALSE, eval = FALSE}
write_ipums_output = function(workbook_name, sheet_name, ipums_data, ipums_var_names, 
                              ipums_freq_tables, output_start_row = 1) {
  # This function writes the IPUMS harmonization output to an excel workbook.
  #
  # Inputs:
  #   workbook_name = Name of the object that identifies the excel workbook in which the output 
  #                   is being stored.
  #   sheet_name = Name of the sheet within workbook_name to which the output should be written.
  #   ipums_data = Name of the IPUMS dataset.
  #   ipums_var_names = Vector of IPUMS variable names indicating the variables that are to be 
  #                     written to sheet_name. Must be the same length as ipums_freq_tables, 
  #                     otherwise the function returns an error message. Must also have a length 
  #                     of no more than 3, otherwise the function returns an error message.
  #   ipums_freq_tables = List of data frames corresponding to the variables listed in ipums_var_names.
  #                       Must be the same length as ipums_var_names, otherwise the function returns 
  #                       an error message. Must also have a length of no more than 3, otherwise the 
  #                       function returns an error message.
  #
  # Returns:
  #   Nothing. The function prints the output to the excel sheet/workbook, as specified by the user.
  #
  
  if (length(ipums_var_names) != length(ipums_freq_tables)) {
    return("Error: ipums_var_names must be the same length as ipums_freq_tables.")
  }
  
  if (length(ipums_var_names) > 3) {
    return("Error: ipums_var_names and ipums_freq_tables must have lengths of no more than 3.")
  }
  
  for (i in 1:length(ipums_var_names)) {
    if (i == 1) {
      writeData(workbook_name, sheet = sheet_name, startRow = output_start_row, "IPUMS 2015")
      writeData(workbook_name, sheet = sheet_name, startRow = output_start_row + 1,
                attr(ipums_data, "variable.labels")[which(attr(ipums_data, "names") == 
                                                            ipums_var_names[i])])
      writeData(workbook_name, sheet = sheet_name, startRow = output_start_row + 3,
                cbind(ipums_freq_tables[[i]][,1], round(ipums_freq_tables[[i]][,2], 0), 
                      round(ipums_freq_tables[[i]][,-c(1,2)], 2)))
    }
    if (i == 2) {
      writeData(workbook_name, sheet = sheet_name, startRow = nrow(ipums_freq_tables[[i - 1]]) + 
                  (output_start_row + 7),
                attr(ipums_data, "variable.labels")[which(attr(ipums_data, "names") == 
                                                            ipums_var_names[i])])
      writeData(workbook_name, sheet = sheet_name, startRow = nrow(ipums_freq_tables[[i - 1]]) + 
                  (output_start_row + 9),
                cbind(ipums_freq_tables[[i]][,1], round(ipums_freq_tables[[i]][,2], 0), 
                      round(ipums_freq_tables[[i]][,-c(1,2)], 2)))
    }
    if (i == 3) {
      writeData(workbook_name, sheet = sheet_name, startRow = nrow(ipums_freq_tables[[i - 2]]) + 
                  nrow(ipums_freq_tables[[i - 1]]) + (output_start_row + 13),
                attr(ipums_data, "variable.labels")[which(attr(ipums_data, "names") == 
                                                            ipums_var_names[i])])
      writeData(workbook_name, sheet = sheet_name, startRow = nrow(ipums_freq_tables[[i - 2]]) + 
                  nrow(ipums_freq_tables[[i - 1]]) + (output_start_row + 15),
                cbind(ipums_freq_tables[[i]][,1], round(ipums_freq_tables[[i]][,2], 0), 
                      round(ipums_freq_tables[[i]][,-c(1,2)], 2)))
    }
  }
}
```




## write_dhs_output

```{r warning = FALSE, eval = FALSE}
write_dhs_output = function(workbook_name, sheet_name, dhs_data, dhs_var_names, 
                            dhs_freq_tables, output_start_row = 1) {
  # This function writes the DHS harmonization output to an excel workbook.
  #
  # Inputs:
  #   workbook_name = Name of the object that identifies the excel workbook in which the output 
  #                   is being stored.
  #   sheet_name = Name of the sheet within workbook_name to which the output should be written.
  #   dhs_data = Name of the DHS dataset.
  #   dhs_var_names = Vector of DHS variable names indicating the variables that are to be 
  #                   written to sheet_name. Must be the same length as dhs_freq_tables, otherwise 
  #                   the function returns an error message. Must also have a length of no more 
  #                   than 3, otherwise the function returns an error message.
  #   dhs_freq_tables = List of data frames corresponding to the variables listed in dhs_var_names. 
  #                     Must be the same length as dhs_var_names, otherwise the function returns an 
  #                     error message. Must also have a length of no more than 3, otherwise the 
  #                     function returns an error message.
  #
  # Returns:
  #   Nothing. The function prints the output to the excel sheet/workbook, as specified by the user.
  #
  
  if (length(dhs_var_names) != length(dhs_freq_tables)) {
    return("Error: dhs_var_names must be the same length as dhs_freq_tables.")
  }
  
  if (length(dhs_var_names) > 3) {
    return("Error: dhs_var_names and dhs_freq_tables must have lengths of no more than 3.")
  }
  
  
  for (i in 1:length(dhs_var_names)) {
    if (i == 1) {
      writeData(workbook_name, sheet = sheet_name, startRow = output_start_row, startCol = 10, 
                "DHS 2019")
      writeData(workbook_name, sheet = sheet_name, startRow = output_start_row + 1, startCol = 10,
                attr(dhs_data, "variable.labels")[which(attr(dhs_data, "names") == 
                                                          dhs_var_names[i])])
      writeData(workbook_name, sheet = sheet_name, startRow = output_start_row + 3, startCol = 10,
                cbind(dhs_freq_tables[[i]][,1], round(dhs_freq_tables[[i]][,2], 0), 
                      round(dhs_freq_tables[[i]][,-c(1,2)], 2)))
    }
    if (i == 2) {
      writeData(workbook_name, sheet = sheet_name, startRow = nrow(dhs_freq_tables[[i - 1]]) + 
                  (output_start_row + 7), startCol = 10,
                attr(dhs_data, "variable.labels")[which(attr(dhs_data, "names") == 
                                                          dhs_var_names[i])])
      writeData(workbook_name, sheet = sheet_name, startRow = nrow(dhs_freq_tables[[i - 1]]) + 
                  (output_start_row + 9), startCol = 10,
                cbind(dhs_freq_tables[[i]][,1], round(dhs_freq_tables[[i]][,2], 0), 
                      round(dhs_freq_tables[[i]][,-c(1,2)], 2)))
    }
    if (i == 3) {
      writeData(workbook_name, sheet = sheet_name, startRow = nrow(dhs_freq_tables[[i - 2]]) + 
                  nrow(dhs_freq_tables[[i - 1]]) + (output_start_row + 13), startCol = 10,
                attr(dhs_data, "variable.labels")[which(attr(dhs_data, "names") == 
                                                          dhs_var_names[i])])
      writeData(workbook_name, sheet = sheet_name, startRow = nrow(dhs_freq_tables[[i - 2]]) + 
                  nrow(dhs_freq_tables[[i - 1]]) + (output_start_row + 15), startCol = 10,
                cbind(dhs_freq_tables[[i]][,1], round(dhs_freq_tables[[i]][,2], 0), 
                      round(dhs_freq_tables[[i]][,-c(1,2)], 2)))
    }
  }
}
```